#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
XLSX_PATH = ROOT / "downloads" / "copypedia_excels_merged(edit).xlsx"
OUTPUT_JS = ROOT / "data" / "copypedia.js"


def slug_fragment(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^0-9a-zA-Z가-힣]+", "-", value)
    return value.strip("-") or "entry"


def build_records() -> list[dict]:
    workbook = load_workbook(XLSX_PATH, read_only=True, data_only=True)
    sheet = workbook["all_rows"]
    records: list[dict] = []
    seen: set[tuple[str, str, str]] = set()

    for index, row in enumerate(sheet.iter_rows(values_only=True), start=1):
        if index == 1:
            continue
        brand = (str(row[0]).strip() if row[0] is not None else "")
        copy = (str(row[1]).strip() if row[1] is not None else "")
        url = (str(row[2]).strip() if row[2] is not None else "")
        if not copy:
            continue

        key = (brand, copy, url)
        if key in seen:
            continue
        seen.add(key)

        record = {
            "id": f"copypedia-{index}-{slug_fragment(brand)}-{slug_fragment(copy)}",
            "brand": brand,
            "campaign": "",
            "copy": copy,
            "sourceUrl": url,
            "sourceType": "첨부 엑셀 아카이브",
            "copyStatus": "collected",
            "collection": "copypedia",
            "collectionLabel": "COPYPEDIA",
        }
        records.append(record)
    return records


def main() -> int:
    records = build_records()
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    OUTPUT_JS.write_text(
        "// Generated by scripts/import_copypedia_xlsx.py\n"
        f"window.COPYPEDIA_ARCHIVE = {payload};\n",
        encoding="utf-8",
    )
    print(json.dumps({"output": str(OUTPUT_JS.relative_to(ROOT)), "recordCount": len(records)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
